# -*- coding: utf-8 -*-
"""English -> Persian exercise-name composer.

ExerciseDB names are compositional: "<equipment> <modifiers> <movement head>"
(e.g. "barbell incline reverse-grip press"). Persian gym naming puts the
movement first and the equipment last: "پرس شیب دست برعکس هالتر". This module
does that reordering with a curated vocabulary, and falls back to an explicit
OVERRIDES table for the idiomatic names a rule engine cannot get right.
"""

import re

from terms import EQUIPMENT_IN_NAME, MUSCLE

# --- movement heads --------------------------------------------------------
# Longest phrase wins. The value is the Persian movement noun; the phrase is
# consumed from the name so its words are not repeated as modifiers.
HEADS = [
    # presses
    ("guillotine press", "پرس گیوتین"),
    ("bench press", "پرس سینه"),
    ("chest press", "پرس سینه"),
    ("shoulder press", "پرس سرشانه"),
    ("military press", "پرس نظامی"),
    ("french press", "پرس فرانسوی"),
    ("leg press", "پرس پا"),
    ("floor press", "پرس زمینی"),
    ("skull crusher", "پرس خوابیده پیشانی"),
    ("skullcrusher", "پرس خوابیده پیشانی"),
    ("skull press", "پرس خوابیده پیشانی"),
    ("jm press", "پرس JM"),
    ("w-press", "پرس W"),
    ("pallof press", "پرس پالوف"),
    ("bradford press", "پرس برادفورد"),
    ("svend press", "پرس سوند"),
    ("presses", "پرس"),
    ("press", "پرس"),
    # curls
    ("leg curl", "پشت پا"),
    ("hamstring curl", "پشت پا"),
    ("wrist curl", "مچ دست"),
    ("preacher curl", "جلو بازو لاری"),
    ("concentration curl", "جلو بازو تمرکزی"),
    ("hammer curl", "جلو بازو چکشی"),
    ("drag curl", "جلو بازو کششی"),
    ("spider curl", "جلو بازو اسپایدر"),
    ("zottman curl", "جلو بازو زوتمن"),
    ("curl-up", "کرل شکم"),
    ("curls", "جلو بازو"),
    ("curl", "جلو بازو"),
    # rows / pulls
    ("upright row", "نشر از جلو با هالتر"),
    ("pendlay row", "زیربغل پندلی"),
    ("t-bar row", "زیربغل تی‌بار"),
    ("lat pulldown", "لت"),
    ("row", "زیربغل"),
    ("pulldown", "لت"),
    ("pushdown", "پشت بازو"),
    ("pullover", "پول‌اور"),
    ("pull-in", "جمع کردن پا"),
    ("pull-ups", "بارفیکس"),
    ("pull-up", "بارفیکس"),
    ("pull up", "بارفیکس"),
    ("pull ups", "بارفیکس"),
    ("chin up", "بارفیکس دست جمع"),
    ("chin", "بارفیکس"),
    ("chin-ups", "بارفیکس دست جمع"),
    ("chin-up", "بارفیکس دست جمع"),
    ("muscle-up", "ماسل‌آپ"),
    ("muscle up", "ماسل‌آپ"),
    ("face pull", "فیس پول"),
    # raises
    ("calf raise", "ساق پا"),
    ("calf raises", "ساق پا"),
    ("lateral raise", "نشر جانبی"),
    ("front raise", "نشر از جلو"),
    ("rear delt raise", "نشر خم"),
    ("leg raise", "بالا آوردن پا"),
    ("hip raise", "بالا آوردن لگن"),
    ("glute-ham raise", "گلوت-هام رِیز"),
    ("y-raise", "نشر Y"),
    ("t-raise", "نشر T"),
    ("raises", "بالا آوردن"),
    ("raise", "بالا آوردن"),
    # extensions
    ("leg extension", "جلو پا"),
    ("back extension", "فیله کمر"),
    ("triceps extension", "پشت بازو"),
    ("tricep extension", "پشت بازو"),
    ("hyperextension", "هایپراکستنشن"),
    ("hyper extension", "هایپراکستنشن"),
    ("extension", "اکستنشن"),
    # chest
    ("rear fly", "نشر خم"),
    ("reverse fly", "نشر خم"),
    ("rear delt fly", "نشر خم"),
    ("fly", "قفسه سینه"),
    ("flyes", "قفسه سینه"),
    ("flys", "قفسه سینه"),
    ("crossover", "کراس‌اور"),
    ("cross-over", "کراس‌اور"),
    ("crossovers", "کراس‌اور"),
    ("push-up", "شنا"),
    ("push up", "شنا"),
    ("pushup", "شنا"),
    ("push-ups", "شنا"),
    ("push ups", "شنا"),
    ("dips", "دیپ"),
    ("dip", "دیپ"),
    # abs
    ("sit-up", "دراز و نشست"),
    ("sit up", "دراز و نشست"),
    ("v-up", "وی‌آپ"),
    ("v-sit", "وی‌سیت"),
    ("l-sit", "ال‌سیت"),
    ("crunches", "کرانچ"),
    ("crunch", "کرانچ"),
    ("plank", "پلانک"),
    ("planche", "پلانچ"),
    ("rack pull", "رک پول"),
    ("back curl", "فیله کمر"),
    ("twists", "چرخش تنه"),
    ("twist", "چرخش تنه"),
    ("wipers", "برف‌پاک‌کن"),
    ("cocoons", "کوکون"),
    ("dead bug", "دد باگ"),
    ("bicycle", "دوچرخه شکم"),
    ("hollow hold", "هالو هولد"),
    # legs
    ("squats", "اسکات"),
    ("squat", "اسکات"),
    ("lunge", "لانژ"),
    ("lunges", "لانژ"),
    ("deadlift", "ددلیفت"),
    ("good morning", "گود مورنینگ"),
    ("step-up", "استپ‌آپ"),
    ("step up", "استپ‌آپ"),
    ("thruster", "تراستر"),
    ("bridge", "پل"),
    ("hip thrust", "هیپ تراست"),
    ("hip thrusts", "هیپ تراست"),
    ("pelvic tilt", "شیب لگن"),
    # shoulders / back
    ("shrug", "شراگ"),
    ("kickback", "کیک‌بک"),
    ("kickbacks", "کیک‌بک"),
    ("shoulder tap", "ضربه شانه"),
    # olympic / power
    ("clean and jerk", "کلین اند جرک"),
    ("clean", "کلین"),
    ("snatch", "اسنچ"),
    ("jerk", "جرک"),
    ("swing", "سوئینگ"),
    ("high pull", "های پول"),
    ("get up", "گت‌آپ"),
    # cardio / conditioning
    ("burpee", "برپی"),
    ("mountain climber", "کوهنورد"),
    ("jumping jack", "جامپینگ جک"),
    ("jack jump", "جامپینگ جک"),
    ("jumps", "پرش"),
    ("jump", "پرش"),
    ("hops", "جهش"),
    ("sprint", "دوی سرعت"),
    ("sprints", "دوی سرعت"),
    ("run", "دویدن"),
    ("walk", "راه رفتن"),
    ("walking", "راه رفتن"),
    ("climb", "بالا رفتن"),
    ("crawl", "خزیدن"),
    ("throw", "پرتاب"),
    ("slam", "کوبیدن"),
    ("carry", "حمل"),
    ("rollerout", "غلتک شکم"),
    ("rollerer", "غلتک شکم"),
    ("roll-out", "غلتک شکم"),
    ("fallout", "فال‌اوت"),
    # mobility
    ("stretch", "کشش"),
    ("rotation", "چرخش"),
    ("rotations", "چرخش"),
    ("circles", "چرخش دایره‌ای"),
    ("pose", "حرکت یوگا"),
    ("hold", "نگه‌داشتن"),
    ("squeeze", "فشردن"),
    ("adduction", "نزدیک کردن"),
    ("hip abductor", "دور کردن ران"),
    ("hip adductor", "نزدیک کردن ران"),
    ("abductor", "دور کردن ران"),
    ("adductor", "نزدیک کردن ران"),
    ("abduction", "دور کردن"),
    ("flexion", "خم کردن"),
    ("pronation", "پرونیشن"),
    ("supination", "سوپینیشن"),
    ("bend", "خم شدن"),
    ("bends", "خم شدن"),
    ("tilt", "شیب دادن"),
    ("touch", "لمس"),
    ("touchers", "لمس"),
    ("reach", "رساندن دست"),
    ("lift", "بلند کردن"),
    ("lifting", "بلند کردن"),
    ("kick", "لگد"),
    ("kicks", "لگد"),
    ("hug", "بغل کردن"),
    ("balance", "تعادل"),
    ("stabilization", "تثبیت"),
    ("march", "راه رفتن درجا"),
    ("swim", "شنا کردن"),
]

# --- modifiers -------------------------------------------------------------
MODIFIERS = {
    "incline": "شیب مثبت",
    "decline": "شیب منفی",
    "flat": "تخت",
    "seated": "نشسته",
    "sitted": "نشسته",
    "sit": "نشسته",
    "standing": "ایستاده",
    "lying": "خوابیده",
    "supine": "به پشت خوابیده",
    "prone": "دمر",
    "reclining": "درازکشیده",
    "kneeling": "زانو زده",
    "squatting": "در حالت اسکات",
    "bent over": "خم",
    "bent-over": "خم",
    "bent": "خم",
    "close grip": "دست جمع",
    "close-grip": "دست جمع",
    "clean-grip": "گرفتن کلین",
    "wide grip": "دست باز",
    "wide-grip": "دست باز",
    "narrow grip": "دست جمع",
    "reverse grip": "دست برعکس",
    "reverse-grip": "دست برعکس",
    "pronate-grip": "دست از رو",
    "neutral grip": "دست خنثی",
    "mixed grip": "دست مخلوط",
    "gripless": "بدون گرفتن دسته",
    "grip": "گرفتن",
    "overhand": "از رو",
    "underhand": "از زیر",
    "pronated": "از رو",
    "supinated": "از زیر",
    "palms": "کف دست",
    "palm": "کف دست",
    "palm-in": "کف دست رو به داخل",
    "reverse": "معکوس",
    "revers": "معکوس",
    "inverse": "معکوس",
    "inverted": "وارونه",
    "one arm": "تک‌دست",
    "single arm": "تک‌دست",
    "unilateral": "تک‌طرفه",
    "one leg": "تک‌پا",
    "single leg": "تک‌پا",
    "single": "تک",
    "one": "تک",
    "two": "دو",
    "three": "سه",
    "double": "دوبل",
    "twin": "دوقلو",
    "alternate": "متناوب",
    "alternating": "متناوب",
    "front": "جلو",
    "rear": "خم",
    "posterior": "خلفی",
    "anterior": "قدامی",
    "side": "پهلو",
    "side-to-side": "پهلو به پهلو",
    "lateral": "جانبی",
    "vertical": "عمودی",
    "horizontal": "افقی",
    "diagonal": "مورب",
    "overhead": "بالای سر",
    "behind": "پشت",
    "head": "سر",
    "behind head": "از پشت سر",
    "behind neck": "از پشت گردن",
    "straight": "صاف",
    "stiff": "صاف",
    "extended": "کشیده",
    "outstretched": "کشیده",
    "raised": "بالا آمده",
    "elevated": "بالا آمده",
    "suspended": "معلق",
    "hanging": "آویزان",
    "hang": "آویزان",
    "supported": "با تکیه‌گاه",
    "support": "تکیه‌گاه",
    "self": "بدون کمک",
    "assisted": "با کمک",
    "weighted": "با وزنه",
    "bodyweight": "با وزن بدن",
    "body weight": "با وزن بدن",
    "high": "بالا",
    "low": "پایین",
    "middle": "میانی",
    "upper": "بالایی",
    "lower": "پایینی",
    "inner": "داخلی",
    "outer": "خارجی",
    "outside": "بیرونی",
    "inside": "درونی",
    "internal": "داخلی",
    "external": "خارجی",
    "wide": "باز",
    "narrow": "جمع",
    "close": "جمع",
    "half": "نیمه",
    "quarter": "یک‌چهارم",
    "full": "کامل",
    "semi": "نیمه",
    "deep": "عمیق",
    "short": "کوتاه",
    "long": "بلند",
    "wall": "دیوار",
    "floor": "زمین",
    "ground": "زمین",
    "bench": "نیمکت",
    "benches": "نیمکت",
    "chair": "صندلی",
    "box": "جعبه",
    "stepbox": "استپ‌باکس",
    "platform": "سکو",
    "parallel bars": "پارالل",
    "parallel": "پارالل",
    "bars": "میله",
    "bar": "میله",
    "rack": "رک",
    "cage": "قفس",
    "pulley": "قرقره",
    "attachment": "دسته",
    "handle": "دسته",
    "strap": "بند",
    "straps": "بند",
    "towel": "حوله",
    "ring": "رینگ",
    "stirrups": "رکاب",
    "pad": "پد",
    "board": "تخته",
    "blaster": "بازو بلستر",
    "arm blaster": "بازو بلستر",
    "twisting": "چرخشی",
    "twisted": "چرخیده",
    "rotational": "چرخشی",
    "rotary": "چرخشی",
    "isometric": "ایزومتریک",
    "dynamic": "پویا",
    "static": "ایستا",
    "negative": "منفی",
    "plyo": "پلایومتریک",
    "explosive": "انفجاری",
    "speed": "سرعتی",
    "quick": "سریع",
    "slow": "آهسته",
    "modified": "اصلاح‌شده",
    "advanced": "پیشرفته",
    "intermediate": "متوسط",
    "basic": "پایه",
    "variation": "نسخه",
    "cross": "ضربدری",
    "archer": "کمانداری",
    "circular": "دایره‌ای",
    "clock": "ساعتی",
    "tuck": "جمع‌شده",
    "pike": "پایک",
    "straddle": "پاباز",
    "split": "اسپلیت",
    "sumo": "سومو",
    "zercher": "زرچر",
    "romanian": "رومانیایی",
    "jefferson": "جفرسون",
    "landmine": "لندماین",
    "goblet": "گابلت",
    "hack": "هک",
    "sissy": "سیسی",
    "pistol": "تک‌پا (پیستول)",
    "cossack": "قزاقی",
    "curtsey": "ضربدری",
    "skater": "اسکیتی",
    "frog": "قورباغه‌ای",
    "frankenstein": "فرانکنشتاین",
    "arnold": "آرنولدی",
    "cuban": "کوبایی",
    "turkish": "ترکی",
    "korean": "کره‌ای",
    "russian": "روسی",
    "hindu": "هندو",
    "judo": "جودو",
    "boxing": "بوکس",
    "kayak": "قایقرانی",
    "farmers": "فارمرز",
    "gorilla": "گوریلی",
    "monster": "مانستر",
    "spider": "اسپایدر",
    "superman": "سوپرمن",
    "handstand": "بالانس روی دست",
    "planche": "پلانچ",
    "flag": "پرچم",
    "maltese": "مالتیز",
    "stalder": "استالدر",
    "gironda": "جیروندا",
    "sternum": "جناغی",
    "scott": "لاری",
    "preacher": "لاری",
    "peacher": "لاری",
    "donkey": "خرکی",
    "renegade": "رنگید",
    "burpee": "برپی",
    "star": "ستاره",
    "scissor": "قیچی",
    "flutter": "پروانه‌ای",
    "windmill": "آسیاب بادی",
    "seesaw": "الاکلنگی",
    "rocking": "گهواره‌ای",
    "rocky": "راکی",
    "clap": "با کف زدن",
    "diamond": "الماسی",
    "pike-to-cobra": "پایک به کبری",
    "sphinx": "ابوالهول",
    "crab": "خرچنگی",
    "bear": "خرسی",
    "stork": "لک‌لکی",
    "butterfly": "پروانه",
    "inchworm": "اینچ‌ورم",
    "jackknife": "جک‌نایف",
    "jack knife": "جک‌نایف",
    "otis-up": "اوتیس‌آپ",
    "prisoner": "دست پشت سر",
    "waiter": "پیشخدمتی",
    "zottman": "زوتمن",
    "tate": "تیت",
    "pin": "پین",
    "drop": "دراپ",
    "depth": "عمقی",
    "kipping": "کیپینگ",
    "l-pull-up": "بارفیکس ال",
    "body-up": "بادی‌آپ",
    "bottoms-up": "وارونه",
    "bottoms": "وارونه",
    "up-down": "بالا-پایین",
    "back and forth": "رفت و برگشت",
    "backward": "به عقب",
    "forward": "به جلو",
    "upward": "رو به بالا",
    "downward": "رو به پایین",
    "around": "دور",
    "through": "از میان",
    "across": "روی",
    "against": "کنار",
    "between": "بین",
    "above": "بالای",
    "under": "زیر",
    "over": "روی",
    "on": "روی",
    "in": "در",
    "to": "به",
    "from": "از",
    "of": "",
    "the": "",
    "a": "",
    "and": "و",
    "with": "با",
    "off": "خارج از",
    "into": "به",
    "all fours": "چهار دست و پا",
    "fours": "چهار دست و پا",
    "yoga": "یوگا",
    "pov": "زاویه دید اول‌شخص",
    "male": "مرد",
    "female": "زن",
    "exercise": "",
    "muscle": "",
    "machine": "دستگاه",
    "trainer": "دستگاه",
    "equipment": "دستگاه",
    "cycle": "دوچرخه",
    "bike": "دوچرخه",
    "treadmill": "تردمیل",
    "ski": "اسکی",
    "skier": "اسکی",
    "sledge": "سورتمه",
    "sled": "سورتمه",
    "tire": "لاستیک",
    "ropes": "طناب",
    "battling": "بتل",
    "medicine": "مدیسن",
    "stability": "تعادلی",
    "bosu": "بوسو",
    "ball": "توپ",
    "wheel": "چرخ",
    "roller": "غلتک",
    "gripper": "گیره دست",
    "iron": "میله",
    "cambered": "خمیده",
    "captains": "کاپیتان",
    "figure": "شکل",
    "8": "۸",
    "180": "۱۸۰",
    "360": "۳۶۰",
    "45": "۴۵",
    "45°": "۴۵ درجه",
    "degrees": "درجه",
    "angle": "زاویه",
    "angled": "زاویه‌دار",
    "range": "دامنه",
    "motion": "حرکت",
    "position": "وضعیت",
    "stance": "حالت",
    "style": "سبک",
    "sequence": "توالی",
    "pyramid": "هرمی",
    "response": "واکنش",
    "point": "نقطه",
    "release": "رها کردن",
    "catch": "گرفتن",
    "multiple": "چندگانه",
    "pass": "عبور",
    "slide": "سُر خوردن",
    "flip": "چرخاندن",
    "rotate": "چرخاندن",
    "spell": "نوشتن",
    "caster": "کستر",
    "world": "دنیا",
    "greatest": "بهترین",
    "impossible": "غیرممکن",
    "anti": "ضد",
    "gravity": "جاذبه",
    "depresor": "پایین‌برنده",
    "retractor": "جمع‌کننده",
    "elevator": "بالابرنده",
    "saw": "اره‌ای",
    "skin the cat": "اسکین د کت",
    "cat": "گربه",
    "skin": "پوست",
    "dog": "سگ",
    "facing": "رو به",
    "big": "بزرگ",
    "pro": "حرفه‌ای",
    "power": "قدرتی",
    "potty": "چمباتمه",
    "squad": "اسکات",
    "air": "هوا",
    "reps": "تکرار",
    "drive": "فشار",
    "hook": "هوک",
    "london": "لندن",
    "runners": "دونده",
    "staircase": "پله",
    "stride": "گام",
    "lean": "متمایل",
    "left": "چپ",
    "right": "راست",
    "contralateral": "ضربدری",
    "ipsilateral": "هم‌سمت",
    "bowling": "بولینگ",
    "tennis ball": "توپ تنیس",
    "tennis": "تنیس",
    "can": "قوطی",
    "breeding": "پرورشی",
    "thibaudeau": "تیبادو",
    "hyght": "هایت",
    "janda": "یاندا",
    "keens": "زانو",
    "plus": "پلاس",
    "clasped": "قفل‌شده",
    "reversed": "برعکس",
    "apart": "باز",
    "closer": "نزدیک‌تر",
    "feet": "پا",
    "legged": "پا",
    "astride": "پاباز",
    "guillotine": "گیوتین",
    "crusher": "کراشر",
    "sz-bar": "هالتر SZ",
    "ez-bar": "هالتر EZ",
    "ez-barbell": "هالتر EZ",
    "ez": "EZ",
    "v-bar": "دسته V",
    "t-bar": "تی‌بار",
    "trap": "تراپ‌بار",
    "olympic": "المپیک",
    "smith": "اسمیت",
    "hammer": "چکشی",
    "leverage": "اهرمی",
    "lever": "دستگاه اهرمی",
    "cable": "سیم‌کش",
    "band": "کش",
    "resistance": "مقاومتی",
    "barbell": "هالتر",
    "dumbbell": "دمبل",
    "dumbbells": "دمبل",
    "kettlebell": "کتل‌بل",
    "elliptical": "الپتیکال",
    "stepmill": "پله‌نورد",
    "stationary": "ثابت",
    "ergometer": "ارگومتر",
    "skierg": "اسکی‌ارگ",
    "vertical": "عمودی",
    "abdominal": "شکم",
    "obliques": "مایل شکم",
    "wrists": "مچ دست",
    "flexor": "خم‌کننده",
    "extensor": "بازکننده",
    "leg-hip": "پا و لگن",
    "quads": "چهارسر ران",
    "glutes": "سرینی",
    "calves": "ساق پا",
    "hamstrings": "همسترینگ",
    "biceps": "جلو بازو",
    "triceps": "پشت بازو",
    "lats": "زیربغل",
    "delts": "سرشانه",
    "traps": "کول",
    "pectoralis": "سینه‌ای",
    "major": "بزرگ",
    "rectus": "راست",
    "femoris": "رانی",
    "gluteus": "سرینی",
    "piriformis": "پیریفورمیس",
    "peroneals": "پرونئال",
    "tibialis": "تیبیالیس",
    "serratus": "دندانه‌ای",
    "scapula": "کتف",
    "scapular": "کتفی",
    "groin": "کشاله ران",
    "core": "مرکز بدن",
    "neck": "گردن",
    "spine": "ستون فقرات",
    "hip": "لگن",
    "hips": "لگن",
    "pelvic": "لگن",
    "knee": "زانو",
    "knees": "زانو",
    "elbow": "آرنج",
    "elbow-to-knee": "آرنج به زانو",
    "ankle": "مچ پا",
    "ankles": "مچ پا",
    "wrist": "مچ دست",
    "shoulder": "شانه",
    "shoulders": "شانه",
    "chest": "سینه",
    "back": "پشت",
    "abs": "شکم",
    "arm": "بازو",
    "arms": "بازو",
    "leg": "پا",
    "legs": "پا",
    "hand": "دست",
    "hands": "دست",
    "toe": "نوک پا",
    "heel": "پاشنه",
    "finger": "انگشت",
    "face": "صورت",
    "body": "بدن",
    "calf": "ساق پا",
    "glute": "سرینی",
    "lat bar": "میله لت",
    "lat": "زیربغل",
    "delt": "سرشانه",
    "deltoid": "دلتوئید",
    "bicep": "جلو بازو",
    "tricep": "پشت بازو",
    "pec": "سینه",
    "oblique": "مایل شکم",
    "hamstring": "همسترینگ",
    "quad": "چهارسر ران",
    "abductor": "دورکننده ران",
    "adductor": "نزدیک‌کننده ران",
    "abductors": "دورکننده‌های ران",
    "adductors": "نزدیک‌کننده‌های ران",
    "iron cross": "صلیب آهنین",
    "vertical bar": "میله عمودی",
    "pull-up bar": "میله بارفیکس",
    "low bar": "میله پایین",
    "high bar": "میله بالا",
    "dip cage": "قفس دیپ",
    "stork stance": "حالت لک‌لکی",
    "rope attachment": "دسته طناب",
    "high pulley": "قرقره بالا",
    "low pulley": "قرقره پایین",
    "wide press": "پرس دست باز",
    "round arm": "چرخش دورانی بازو",
    "3 point stance": "حالت سه‌نقطه‌ای",
    "full range": "دامنه کامل",
    "exercise ball": "توپ تعادلی",
    "stability ball": "توپ تعادلی",
    "bosu ball": "توپ بوسو",
    "medicine ball": "مدیسن‌بال",
    "wheel roller": "غلتک چرخ",
    "back pov": "نمای پشت",
    "side pov": "نمای پهلو",
    "front pov": "نمای جلو",
    "swimmer": "شناگر",
    "both": "هر دو",
    "step": "استپ",
    "tap": "ضربه",
    "round": "دورانی",
    "ball": "توپ",
    "boxing": "بوکس",
    "pull": "کشیدن",
    "push": "فشار",
    "row": "زیربغل",
    "shoulder": "شانه",
    "hook": "هوک",
    "rope": "طناب",
    "up": "بالا",
    "down": "پایین",
    "neutral": "خنثی",
    "chin": "چانه",
    "slingers": "چرخش دست",
    "jm": "JM",
    "ab": "شکم",
    "sz": "SZ",
    "t": "تی",
    "otis": "اوتیس",
    "pirate": "دزد دریایی",
    "supper": "شام",
    "out": "بیرون",
    "two-one": "دو به یک",
    "hyper": "هایپر",
    "hook": "هوک",
    "concentration": "تمرکزی",
    "flexion": "خم کردن",
    "bicycle": "دوچرخه",
    "bradford": "برادفورد",
    "circles": "چرخش دایره‌ای",
    "cross-over": "کراس‌اور",
    "crossover": "کراس‌اور",
    "ups": "بالا آوردن",
    "jack": "جک",
    "tilt": "شیب",
    "balance": "تعادل",
    "upright": "عمودی",
    "rotation": "چرخش",
}

# Words that add nothing once the head is chosen.
DROP = {"exercise", "muscle", "the", "a", "of", "v", "variation", "machine"}

# --- explicit overrides ----------------------------------------------------
# Idiomatic names the compositional engine gets wrong or clumsy.
OVERRIDES = {
    "3/4 sit-up": "دراز و نشست سه‌چهارم",
    "back and forth step": "استپ رفت و برگشت",
    "inchworm": "اینچ‌ورم",
    "inchworm v. 2": "اینچ‌ورم نسخه ۲",
    "assisted hanging knee raise with throw down": "بالا آوردن زانو آویزان با رها کردن به پایین (با کمک)",
    "assisted lying leg raise with throw down": "بالا آوردن پا خوابیده با رها کردن به پایین (با کمک)",
    "assisted lying leg raise with lateral throw down": "بالا آوردن پا خوابیده با رها کردن جانبی به پایین (با کمک)",
    "weighted close grip chin-up on dip cage": "بارفیکس دست جمع با وزنه روی قفس دیپ",
    "wheel rollerout": "غلتک شکم با چرخ",
    "reclining big toe pose with rope": "حرکت یوگای درازکشیده شست پا با طناب",
    "standing hamstring and calf stretch with strap": "کشش ایستاده همسترینگ و ساق پا با بند",
    "45° side bend": "خم شدن پهلو ۴۵ درجه",
    "air bike": "دوچرخه هوایی (شکم)",
    "all fours squad stretch": "کشش چهارسر ران چهار دست و پا",
    "alternate heel touchers": "لمس متناوب پاشنه",
    "ankle circles": "چرخش مچ پا",
    "back lever": "بک لِوِر",
    "front lever": "فرانت لِوِر",
    "front lever reps": "تکرار فرانت لِوِر",
    "balance board": "تخته تعادل",
    "band assisted pull-up": "بارفیکس با کمک کش",
    "band jack knife sit-up": "جک‌نایف با کش",
    "bear crawl": "خزیدن خرسی",
    "bodyweight squatting row": "زیربغل اسکات با وزن بدن",
    "butt-ups": "بات‌آپ (پلانک به شیب)",
    "butterfly yoga pose": "حرکت یوگای پروانه",
    "cocoons": "کوکون (جمع کردن زانو خوابیده)",
    "crab twist toe touch": "لمس نوک پا خرچنگی با چرخش",
    "dead bug": "دد باگ",
    "donkey calf raise": "ساق پا خرکی",
    "weighted donkey calf raise": "ساق پا خرکی با وزنه",
    "lever donkey calf raise": "ساق پا خرکی با دستگاه اهرمی",
    "flutter kicks": "ضربات پروانه‌ای پا",
    "groin crunch": "کرانچ کشاله ران",
    "hug keens to chest": "بغل کردن زانوها به سینه",

    "jackknife sit-up": "دراز و نشست جک‌نایف",
    "jack jump": "جامپینگ جک",
    "iron cross stretch": "کشش صلیب آهنین",
    "mountain climber": "کوهنورد",
    "otis-up": "اوتیس‌آپ",
    "potty squat": "اسکات چمباتمه",
    "prisoner half sit-up": "نیمه دراز و نشست با دست پشت سر",
    "push-up plus": "شنا پلاس",
    "russian twist": "چرخش روسی",
    "scapular pull-up": "بارفیکس کتفی",
    "sit-up v. 2": "دراز و نشست نسخه ۲",
    "skin the cat": "اسکین د کت",
    "superman push-up": "شنا سوپرمن",
    "upward facing dog": "سگ رو به بالا (یوگا)",
    "world greatest stretch": "بهترین کشش دنیا",
    "wind sprints": "دوی سرعت تناوبی",
    "ez barbell spider curl": "جلو بازو اسپایدر با هالتر EZ",
    "ez bar standing french press": "پرس فرانسوی ایستاده با هالتر EZ",
    "smith standing military press": "پرس نظامی ایستاده با دستگاه اسمیت",
    "barbell lying preacher curl": "جلو بازو لاری خوابیده با هالتر",
    "barbell bent over row": "زیربغل هالتر خم",
    "lever back extension": "فیله کمر با دستگاه اهرمی",
    "lever assisted chin-up": "بارفیکس دست جمع با کمک دستگاه",
    "hanging straight twisting leg hip raise": "بالا آوردن لگن آویزان با پای صاف و چرخش",
    "side bridge hip abduction": "دور کردن ران در پل پهلو",
    "side hip abduction": "دور کردن ران از پهلو",
    "side lying hip adduction": "نزدیک کردن ران در حالت خوابیده به پهلو",
    "assisted lying calves stretch": "کشش ساق پا خوابیده با کمک",
    "assisted lying glutes stretch": "کشش سرینی خوابیده با کمک",
    "assisted lying gluteus and piriformis stretch": "کشش سرینی و پیریفورمیس خوابیده با کمک",
    "stationary bike run v. 3": "رکاب زدن روی دوچرخه ثابت نسخه ۳",
    "astride jumps": "پرش پاباز",
    "star jump": "پرش ستاره",
    "scissor jumps": "پرش قیچی",
    "semi squat jump": "پرش نیمه اسکات",
    "half knee bends": "نیمه خم کردن زانو",
    "kneeling push-up": "شنا زانو زده",
    "modified hindu push-up": "شنا هندو اصلاح‌شده",
    "chest tap push-up": "شنا با ضربه به سینه",
    "arms apart circular toe touch": "لمس دایره‌ای نوک پا با دست‌های باز",
    "hands clasped circular toe touch": "لمس دایره‌ای نوک پا با دست‌های قفل‌شده",
    "hands reversed clasped circular toe touch": "لمس دایره‌ای نوک پا با دست‌های قفل‌شده برعکس",
    "basic toe touch": "لمس ساده نوک پا",
    "two toe touch": "لمس نوک پا با دو دست",
    "side-to-side toe touch": "لمس نوک پا از پهلو به پهلو",
    "arms overhead full sit-up": "دراز و نشست کامل با دست‌های بالای سر",
    "bent knee lying twist": "چرخش تنه خوابیده با زانوی خم",
    "dynamic chest stretch": "کشش پویای سینه",
    "seated calf stretch": "کشش ساق پا نشسته",
    "forward lunge": "لانژ به جلو",
    "weighted cossack squats": "اسکات قزاقی با وزنه",
    "swimmer kicks v. 2": "ضربات پای شناگر نسخه ۲",
    "kneeling plank tap shoulder": "پلانک زانو زده با ضربه شانه",
    "glute bridge march": "پل سرینی با راه رفتن درجا",
    "glute bridge two legs on bench": "پل سرینی با دو پا روی نیمکت",
    "barbell glute bridge two legs on bench": "پل سرینی هالتر با دو پا روی نیمکت",
    "low glute bridge on floor": "پل سرینی کوتاه روی زمین",
    "barbell glute bridge": "پل سرینی با هالتر",
    "resistance band hip thrusts on knees": "هیپ تراست زانو زده با کش مقاومتی",
    "cable kneeling rear delt row (with rope)": "زیربغل خم زانو زده با سیم‌کش (طناب)",
    "band fixed back close grip pulldown": "لت دست جمع با کش و تکیه‌گاه ثابت",
    "band fixed back underhand pulldown": "لت دست از زیر با کش و تکیه‌گاه ثابت",
    "band two legs calf raise - (band under both legs) v. 2": "ساق پا با کش زیر هر دو پا نسخه ۲",
    "dumbbell over bench one arm wrist curl": "مچ دست تک‌دست روی نیمکت با دمبل",
    "dumbbell over bench wrist curl": "مچ دست روی نیمکت با دمبل",
    "dumbbell high curl": "جلو بازو بالا با دمبل",
    "dumbbell lying wide curl": "جلو بازو باز خوابیده با دمبل",
    "standing single leg curl": "پشت پا تک‌پا ایستاده",
    "weighted standing curl": "جلو بازو ایستاده با وزنه",
    "ez-bar biceps curl (with arm blaster)": "جلو بازو با هالتر EZ و بازو بلستر",
    "barbell biceps curl (with arm blaster)": "جلو بازو با هالتر و بازو بلستر",
    "spider crawl push up": "شنا با خزیدن اسپایدر",
    "dumbbell one arm reverse spider curl": "جلو بازو اسپایدر معکوس تک‌دست با دمبل",
    "dumbbell reverse spider curl": "جلو بازو اسپایدر معکوس با دمبل",
    "kettlebell lunge pass through": "لانژ کتل‌بل با عبور وزنه",
    "barbell drag curl": "جلو بازو کششی با هالتر",
    "band alternating biceps curl": "جلو بازو متناوب با کش",
    "band concentration curl": "جلو بازو تمرکزی با کش",
    "band wrist curl": "مچ دست با کش",
    "barbell alternate biceps curl": "جلو بازو متناوب با هالتر",
    "barbell curl": "جلو بازو با هالتر",
    "band one arm standing low row": "زیربغل تک‌دست ایستاده از پایین با کش",
    "band one arm twisting seated row": "زیربغل تک‌دست نشسته چرخشی با کش",
    "band squat row": "زیربغل در حالت اسکات با کش",
    "band standing rear delt row": "زیربغل خم ایستاده با کش",
    "barbell incline row": "زیربغل شیب مثبت با هالتر",
    "barbell one arm bent over row": "زیربغل تک‌دست خم با هالتر",
    "barbell pendlay row": "زیربغل پندلی با هالتر",
    "barbell reverse grip bent over row": "زیربغل خم دست برعکس با هالتر",
    "lever bent over row": "زیربغل خم با دستگاه اهرمی",
    "lever alternating narrow grip seated row": "زیربغل نشسته دست جمع متناوب با دستگاه اهرمی",
    "barbell floor calf raise": "ساق پا روی زمین با هالتر",
    "barbell seated calf raise": "ساق پا نشسته با هالتر",
    "barbell standing calf raise": "ساق پا ایستاده با هالتر",
    "bodyweight standing calf raise": "ساق پا ایستاده با وزن بدن",
    "cable standing calf raise": "ساق پا ایستاده با سیم‌کش",
    "calf push stretch with hands against wall": "کشش ساق پا با فشار دست به دیوار",
    "barbell close-grip bench press": "پرس سینه دست جمع با هالتر",
    "barbell incline close grip bench press": "پرس سینه شیب مثبت دست جمع با هالتر",
    "barbell incline reverse-grip press": "پرس شیب مثبت دست برعکس با هالتر",
    "barbell reverse close-grip bench press": "پرس سینه دست جمع برعکس با هالتر",
    "barbell reverse grip decline bench press": "پرس سینه شیب منفی دست برعکس با هالتر",
    "barbell reverse grip incline bench press": "پرس سینه شیب مثبت دست برعکس با هالتر",
}
