# -*- coding: utf-8 -*-
"""Persian gym terminology used to re-localize the exercise catalog.

The shipped data/exercises-fa/exercises.fa.json was machine-translated from the
English ExerciseDB catalog and produced names that are wrong or embarrassing in
Persian ("آدم ربایان" for abductors, "گوساله ها" for calves, "لات" for lats,
"مطبوعات نظامی" for military press, "هالتر دروغ گفتن واعظ حلقه" for barbell
lying preacher curl). This module holds the curated replacement vocabulary;
relocalize.py applies it.
"""

# --- taxonomy fields -------------------------------------------------------

BODY_PART = {
    "back": "پشت",
    "cardio": "هوازی",
    "chest": "سینه",
    "lower arms": "ساعد",
    "lower legs": "ساق پا",
    "neck": "گردن",
    "shoulders": "شانه",
    "upper arms": "بازو",
    "upper legs": "ران",
    "waist": "میان‌تنه",
}

EQUIPMENT = {
    "assisted": "با کمک دستگاه",
    "band": "کش",
    "barbell": "هالتر",
    "body weight": "وزن بدن",
    "bosu ball": "توپ بوسو",
    "cable": "سیم‌کش",
    "dumbbell": "دمبل",
    "elliptical machine": "دستگاه الپتیکال",
    "ez barbell": "هالتر EZ",
    "hammer": "چکش",
    "kettlebell": "کتل‌بل",
    "leverage machine": "دستگاه اهرمی",
    "medicine ball": "مدیسن‌بال",
    "olympic barbell": "هالتر المپیک",
    "resistance band": "کش مقاومتی",
    "roller": "غلتک",
    "rope": "طناب",
    "skierg machine": "دستگاه اسکی‌ارگ",
    "sled machine": "دستگاه سورتمه",
    "smith machine": "دستگاه اسمیت",
    "stability ball": "توپ تعادلی",
    "stationary bike": "دوچرخه ثابت",
    "stepmill machine": "دستگاه پله‌نورد",
    "tire": "لاستیک",
    "trap bar": "هالتر تراپ‌بار",
    "upper body ergometer": "ارگومتر بالاتنه",
    "weighted": "با وزنه",
    "wheel roller": "غلتک چرخ",
}

# Equipment as it reads inside an exercise name (suffix position). "body weight"
# and "weighted" are qualifiers rather than tools, so they render differently.
EQUIPMENT_IN_NAME = dict(EQUIPMENT)
EQUIPMENT_IN_NAME.update({
    "body weight": "با وزن بدن",
    "weighted": "با وزنه",
    "assisted": "با کمک دستگاه",
})

MUSCLE = {
    "abdominals": "شکم",
    "abductors": "دورکننده‌های ران",
    "abductor": "دورکننده ران",
    "adductors": "نزدیک‌کننده‌های ران",
    "adductor": "نزدیک‌کننده ران",
    "abs": "شکم",
    "ankle stabilizers": "تثبیت‌کننده‌های مچ پا",
    "ankles": "مچ پا",
    "biceps": "جلو بازو",
    "calves": "ساق پا",
    "cardiovascular system": "دستگاه قلبی-عروقی",
    "chest": "سینه",
    "core": "مرکز بدن",
    "deltoids": "دلتوئید",
    "delts": "سرشانه",
    "forearms": "ساعد",
    "glutes": "سرینی",
    "hamstrings": "همسترینگ",
    "hands": "دست",
    "hip flexors": "خم‌کننده‌های ران",
    "latissimus dorsi": "پشتی بزرگ",
    "lats": "زیربغل",
    "levator scapulae": "بالابرنده کتف",
    "lower back": "کمر",
    "obliques": "مایل شکم",
    "pectorals": "سینه",
    "quadriceps": "چهارسر ران",
    "quads": "چهارسر ران",
    "rhomboids": "رومبوئید",
    "rotator cuff": "روتاتور کاف",
    "serratus anterior": "دندانه‌ای قدامی",
    "shoulders": "شانه",
    "soleus": "نعلی",
    "spine": "ستون فقرات",
    "trapezius": "کول",
    "traps": "کول",
    "triceps": "پشت بازو",
    "upper back": "بالای پشت",
    "wrist extensors": "بازکننده‌های مچ دست",
    "wrist flexors": "خم‌کننده‌های مچ دست",
    "wrists": "مچ دست",
    "piriformis": "پیریفورمیس",
    "rectus femoris": "راست رانی",
    "pectoralis major": "سینه‌ای بزرگ",
    "gluteus": "سرینی",
    "peroneals": "پرونئال",
    "tibialis": "تیبیالیس",
    "femoral": "همسترینگ",
    "quad": "چهارسر ران",
    "groin": "کشاله ران",
    "hip": "لگن",
    "knee": "زانو",
    "elbow": "آرنج",
    "scapula": "کتف",
    "scapular": "کتفی",
    "neck": "گردن",
    "shoulder": "شانه",
    "wrist": "مچ دست",
    "ankle": "مچ پا",
    "back": "پشت",
    "leg": "پا",
    "legs": "پا",
    "arm": "بازو",
    "arms": "بازو",
    "hand": "دست",
    "toe": "نوک پا",
    "heel": "پاشنه",
    "finger": "انگشت",
    "pec": "سینه",
    "oblique": "مایل شکم",
    "hamstring": "همسترینگ",
    "calf": "ساق پا",
    "glute": "سرینی",
    "bicep": "جلو بازو",
    "tricep": "پشت بازو",
    "lat": "زیربغل",
    "delt": "سرشانه",
    "deltoid": "دلتوئید",
    "trap": "کول",
    "spine": "ستون فقرات",
    "chest": "سینه",
    "abdominal": "شکم",
    "knees": "زانو",
    "ankles": "مچ پا",
    "hands": "دست",
}


# --- instruction-body repairs ---------------------------------------------
# The translated instruction paragraphs carry the same bad terminology as the
# names did. Ordered longest-first; applied as plain substring replacements.
INSTRUCTION_FIXES = [
    ("دستگاه استپ آسیاب", "دستگاه پله‌نورد"),
    ("استپ آسیاب", "پله‌نورد"),
    ("نیمکت واعظ", "نیمکت لاری"),
    ("واعظ", "لاری"),
    ("توپ پزشکی", "مدیسن‌بال"),
    ("نشیمنگاه", "صندلی"),
    ("هسته خود را", "عضلات مرکزی بدن خود را"),
    ("هسته را", "عضلات مرکزی بدن را"),
    ("هسته ی خود", "عضلات مرکزی بدن خود"),
    ("تله های خود", "عضلات کول خود"),
    ("تله های", "عضلات کول"),
    ("تله ها را", "عضلات کول را"),
    ("لات خود", "عضلات زیربغل خود"),
    ("لات های خود", "عضلات زیربغل خود"),
    ("گوساله های خود", "ساق پای خود"),
    ("گوساله های", "ساق پا"),
    ("گوساله ها", "ساق پا"),
    ("گوساله خود", "ساق پای خود"),
    ("حلقه دوسر بازویی", "حرکت جلو بازو"),
    ("حلقه دوسر", "جلو بازو"),
    ("آدم ربایان", "دورکننده‌های ران"),
    ("عضلات ربوده", "دورکننده‌های ران"),
    ("مطبوعات نظامی", "پرس نظامی"),
    ("ماشین اهرمی", "دستگاه اهرمی"),
    ("دستگاه اهرم", "دستگاه اهرمی"),
    ("ماشین سورتمه", "دستگاه سورتمه"),
    ("ماشین اسکی", "دستگاه اسکی‌ارگ"),
    ("دستگاه بیضوی", "دستگاه الپتیکال"),
    ("نوار تله", "هالتر تراپ‌بار"),
]
