package controllers

import (
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"
	"strings"

	"github.com/gin-gonic/gin"
)

// TimedComment represents a single comment with timing information
type TimedComment struct {
	Username        string   `json:"username"`
	Message         string   `json:"message"`
	IsAdmin         *bool    `json:"isAdmin,omitempty"`
	TimeOffset      *float64 `json:"timeOffset,omitempty"`
	OffsetSeconds   *float64 `json:"offsetSeconds,omitempty"`
	ReplyToUsername *string  `json:"replyToUsername,omitempty"`
	ReplyToMessage  *string  `json:"replyToMessage,omitempty"`
}

// TimeRange represents a time range with comments
type TimeRange struct {
	Start          string         `json:"start"`
	End            string         `json:"end"`
	StartTimeVideo *string        `json:"startTimeVideo,omitempty"`
	EndTimeVideo   *string        `json:"endTimeVideo,omitempty"`
	Comments       []TimedComment `json:"comments"`
}

// TimedCommentsData represents the entire comments structure (for future use if needed)
type TimedCommentsData struct {
	TimeRanges []TimeRange `json:"timeRanges"`
}

// GetTimedCommentsFilePath returns the path to the timed comments file
func GetTimedCommentsFilePath() string {
	possiblePaths := []string{
		"../src/data/timedComments.ts",
		"../../src/data/timedComments.ts",
		"./src/data/timedComments.ts",
		"src/data/timedComments.ts",
	}

	for _, path := range possiblePaths {
		if _, err := os.Stat(path); err == nil {
			return path
		}
	}

	// Default fallback
	return "../src/data/timedComments.ts"
}

// GetTimedComments reads and returns the raw TypeScript file content
// Frontend will parse it using the existing TypeScript interfaces
func GetTimedComments(c *gin.Context) {
	filePath := GetTimedCommentsFilePath()

	data, err := ioutil.ReadFile(filePath)
	if err != nil {
		log.Printf("❌ Error reading timed comments file: %v", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to read comments file"})
		return
	}

	c.Data(http.StatusOK, "text/typescript", data)
}

// UpdateTimedComments updates the timed comments file based on JSON body
func UpdateTimedComments(c *gin.Context) {
	var req struct {
		TimeRanges []TimeRange `json:"timeRanges" binding:"required"`
	}

	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid request: " + err.Error()})
		return
	}

	filePath := GetTimedCommentsFilePath()

	tsContent := generateTypeScriptFile(req.TimeRanges)

	if err := ioutil.WriteFile(filePath, []byte(tsContent), 0644); err != nil {
		log.Printf("❌ Error writing timed comments file: %v", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to write comments file"})
		return
	}

	log.Printf("✅ Timed comments file updated successfully")
	c.JSON(http.StatusOK, gin.H{
		"message":    "Comments updated successfully",
		"timeRanges": req.TimeRanges,
	})
}

// generateTypeScriptFile generates TypeScript file content from time ranges
func generateTypeScriptFile(timeRanges []TimeRange) string {
	var b strings.Builder

	b.WriteString(`// Timed comments based on video playback time
// This file is auto-generated by the backend. Do not edit manually.

export interface TimedComment {
  username: string;
  message: string;
  isAdmin?: boolean;
  timeOffset?: number; // seconds from start of this time range
  offsetSeconds?: number; // optional alias for timeOffset
  replyToUsername?: string; // username of the message being replied to
  replyToMessage?: string; // content of the message being replied to
}

export interface TimeRange {
  start: string; // time format: "HH:MM:SS:MS"
  end: string;   // time format: "HH:MM:SS:MS"
  startTimeVideo?: string; // optional alias for start
  endTimeVideo?: string;   // optional alias for end
  comments: TimedComment[];
}

export const timedComments: TimeRange[] = [
`)

	for i, tr := range timeRanges {
		b.WriteString("  {\n")
		b.WriteString(fmt.Sprintf("    start: \"%s\",\n", escapeString(tr.Start)))
		b.WriteString(fmt.Sprintf("    end: \"%s\",\n", escapeString(tr.End)))

		if tr.StartTimeVideo != nil {
			b.WriteString(fmt.Sprintf("    startTimeVideo: \"%s\",\n", escapeString(*tr.StartTimeVideo)))
		}
		if tr.EndTimeVideo != nil {
			b.WriteString(fmt.Sprintf("    endTimeVideo: \"%s\",\n", escapeString(*tr.EndTimeVideo)))
		}

		b.WriteString("    comments: [\n")

		for j, cm := range tr.Comments {
			b.WriteString("      { ")
			b.WriteString(fmt.Sprintf("username: \"%s\", ", escapeString(cm.Username)))
			b.WriteString(fmt.Sprintf("message: \"%s\"", escapeString(cm.Message)))

			if cm.IsAdmin != nil && *cm.IsAdmin {
				b.WriteString(", isAdmin: true")
			}
			if cm.TimeOffset != nil {
				b.WriteString(fmt.Sprintf(", timeOffset: %g", *cm.TimeOffset))
			} else if cm.OffsetSeconds != nil {
				b.WriteString(fmt.Sprintf(", timeOffset: %g", *cm.OffsetSeconds))
			}
			if cm.ReplyToUsername != nil {
				b.WriteString(fmt.Sprintf(", replyToUsername: \"%s\"", escapeString(*cm.ReplyToUsername)))
			}
			if cm.ReplyToMessage != nil {
				b.WriteString(fmt.Sprintf(", replyToMessage: \"%s\"", escapeString(*cm.ReplyToMessage)))
			}

			b.WriteString(" }")
			if j < len(tr.Comments)-1 {
				b.WriteString(",")
			}
			b.WriteString("\n")
		}

		b.WriteString("    ]\n")
		b.WriteString("  }")
		if i < len(timeRanges)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}

	b.WriteString("];\n")
	return b.String()
}

// escapeString escapes special characters in strings for TypeScript
func escapeString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", "\\n")
	s = strings.ReplaceAll(s, "\r", "\\r")
	s = strings.ReplaceAll(s, "\t", "\\t")
	return s
}
