package models

// AllModels returns every GORM entity registered in the application.
// Used by migrations and the dev seed loader so new models are added in one place.
func AllModels() []any {
	return []any{
		&User{},
		&CoachProfile{},
		&CoachAchievement{},
		&ServicePlan{},
		&Subscription{},
		&Transaction{},
		&RefreshToken{},
		&UserPhoto{},
		&WorkoutProgram{},
		&NutritionProgram{},
		&ProgramItem{},
		&ProgramItemSet{},
		&NutritionItem{},
		&CheckIn{},
		&DailyCheckIn{},
		&WeeklyCheckIn{},
		&Notification{},
		&Order{},
		&OrderItem{},
		&SiteSettings{},
		&Feedback{},
		&Ticket{},
		&OtpCode{},
		&Exercise{},
		&Food{},
		&FoodServingUnit{},
		&DailyFoodLog{},
		&WorkoutSession{},
		&FunnelLead{},
		&WorkoutSetLog{},
		&PersonalRecord{},
		&WorkoutTemplate{},
		&TemplateProgramItem{},
		&TemplateProgramItemSet{},
		&NutritionTemplate{},
		&TemplateMeal{},
		&TemplateMealItem{},
		&MobileDevice{},
		&MobileStoreRelease{},
		&AIRequestLog{},
		&Recipe{},
		&ProgressReport{},
		&PoseBank{},
		&AchievementRule{},
		&UserAchievement{},
		&XPLedgerEntry{},
		&UserGameStats{},
		&CommunityPost{},
		&PostComment{},
		&PostLike{},
		&Event{},
		&EventParticipation{},
		&MotivationalQuote{},
		&CoachSession{},
		&CoachReview{},
		&GuaranteeCase{},
	}
}
